# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from taskrunner.grpc.protos import taskrunner_pb2 as taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in taskrunner/grpc/protos/taskrunner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/taskrunner.v1.Scheduler/SubmitTask',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/taskrunner.v1.Scheduler/RegisterWorker',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/taskrunner.v1.Scheduler/Heartbeat',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReserveTask = channel.unary_unary(
                '/taskrunner.v1.Scheduler/ReserveTask',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/taskrunner.v1.Scheduler/ReportResult',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/taskrunner.v1.Scheduler/CancelTask',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
                _registered_method=True)
        self.RetryTask = channel.unary_unary(
                '/taskrunner.v1.Scheduler/RetryTask',
                request_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.SerializeToString,
                response_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
                _registered_method=True)


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReserveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveTask,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.SerializeToString,
            ),
            'RetryTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryTask,
                    request_deserializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.FromString,
                    response_serializer=taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'taskrunner.v1.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('taskrunner.v1.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/SubmitTask',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/RegisterWorker',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/Heartbeat',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/ReserveTask',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReserveTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/ReportResult',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/CancelTask',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/taskrunner.v1.Scheduler/RetryTask',
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.TaskMutationRequest.SerializeToString,
            taskrunner_dot_grpc_dot_protos_dot_taskrunner__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
